SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `categories` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `departments` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `qualifications` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `email` varchar(100) NOT NULL, `password_hash` varchar(255) NOT NULL, `role` enum('admin','hr','user') NOT NULL, `is_sarkari_hr` tinyint(1) NOT NULL DEFAULT 0, `status` enum('pending_verification','active','suspended') NOT NULL DEFAULT 'pending_verification', `verification_token` varchar(100) DEFAULT NULL, `token_expiry` datetime DEFAULT NULL, `created_at` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), UNIQUE KEY `email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `private_jobs` ( `id` int(11) NOT NULL AUTO_INCREMENT, `hr_id` int(11) NOT NULL, `title` varchar(255) NOT NULL, `description` text NOT NULL, `category_id` int(11) DEFAULT NULL, `location` varchar(150) DEFAULT NULL, `posted_at` timestamp NOT NULL DEFAULT current_timestamp(), `expiry_date` date DEFAULT NULL, PRIMARY KEY (`id`), KEY `hr_id` (`hr_id`), CONSTRAINT `private_jobs_ibfk_1` FOREIGN KEY (`hr_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `sarkari_notifications` ( `id` int(11) NOT NULL AUTO_INCREMENT, `posted_by` int(11) NOT NULL, `type` enum('job','result','admit_card') NOT NULL, `title` varchar(255) NOT NULL, `description` text NOT NULL, `department_id` int(11) DEFAULT NULL, `qualification_id` int(11) DEFAULT NULL, `official_link` varchar(512) DEFAULT NULL, `upload_path` varchar(255) DEFAULT NULL, `posted_at` timestamp NOT NULL DEFAULT current_timestamp(), `expiry_date` date DEFAULT NULL, `is_moderated` tinyint(1) NOT NULL DEFAULT 1, PRIMARY KEY (`id`), KEY `posted_by` (`posted_by`), KEY `idx_sarkari_type` (`type`), CONSTRAINT `sarkari_notifications_ibfk_1` FOREIGN KEY (`posted_by`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `sarkari_sub_posts` ( `id` int(11) NOT NULL AUTO_INCREMENT, `notification_id` int(11) NOT NULL, `title` varchar(255) NOT NULL, `details` text DEFAULT NULL, PRIMARY KEY (`id`), KEY `notification_id` (`notification_id`), CONSTRAINT `sarkari_sub_posts_ibfk_1` FOREIGN KEY (`notification_id`) REFERENCES `sarkari_notifications` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `job_applications` ( `id` int(11) NOT NULL AUTO_INCREMENT, `job_id` int(11) NOT NULL, `user_id` int(11) NOT NULL, `resume_path` varchar(255) NOT NULL, `status` enum('applied','viewed','shortlisted','rejected') NOT NULL DEFAULT 'applied', `applied_at` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), UNIQUE KEY `unique_application` (`job_id`,`user_id`), KEY `user_id` (`user_id`), CONSTRAINT `job_applications_ibfk_1` FOREIGN KEY (`job_id`) REFERENCES `private_jobs` (`id`) ON DELETE CASCADE, CONSTRAINT `job_applications_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `hr_chat` ( `id` bigint(20) NOT NULL AUTO_INCREMENT, `sender_id` int(11) NOT NULL, `receiver_id` int(11) NOT NULL, `message` text NOT NULL, `is_read` tinyint(1) NOT NULL DEFAULT 0, `timestamp` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), KEY `sender_id` (`sender_id`), KEY `receiver_id` (`receiver_id`), KEY `idx_chat_users` (`sender_id`,`receiver_id`), CONSTRAINT `hr_chat_ibfk_1` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `hr_chat_ibfk_2` FOREIGN KEY (`receiver_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `hr_recommendations` ( `id` int(11) NOT NULL AUTO_INCREMENT, `recommender_id` int(11) NOT NULL, `recommended_user_id` int(11) NOT NULL, `receiver_hr_id` int(11) NOT NULL, `message` text DEFAULT NULL, `created_at` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), KEY `recommender_id` (`recommender_id`), KEY `recommended_user_id` (`recommended_user_id`), KEY `receiver_hr_id` (`receiver_hr_id`), CONSTRAINT `hr_recommendations_ibfk_1` FOREIGN KEY (`recommender_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `hr_recommendations_ibfk_2` FOREIGN KEY (`recommended_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE, CONSTRAINT `hr_recommendations_ibfk_3` FOREIGN KEY (`receiver_hr_id`) REFERENCES `users` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
